### ISSUE TITLE
FEAT: Implementar filtro de empréstimos por armário

### ISSUE THREAD

**Issue by terenciani** [marceloTerencianiIFPR/ArmariosIFPR#42]
COMO servidor
QUERO poder filtrar os empréstimos por armário
PARA obter um histórico detalhado de quais estudantes que o pegaram.

Pode ser um filtro em empréstimos ou uma área relacionada aos armários.

**Comment by OAllanFernando** [comment]
Implementado na fix-listagem-por-ativos
